name = "Light"
license = "N/A"
licenselink = ""
description = "Digital Insanity is blog theme for hugo that I use in https://brunoamaral.eu/. It's built using bootstrap, with ideas and typography from Pixelarity's Future Imperfect Theme."
tags = ["blog", "bootstrap"]
features = ["blog"]
min_version = 0.14

[author]
    name = "Bruno Amaral"
    homepage = "http://brunoamaral.eu/"

